name: eduverse_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.2
  
  video_player: ^2.8.6
  chewie: ^1.8.1
  flutter_spinkit: ^5.2.0
  model_viewer_plus: ^1.7.0
  google_generative_ai: any

  # Utilities
  supabase_flutter: ^2.0.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true